cache_dir: ./data/

# 触发的命令
comm:

  bind: 卡池绑定

  #
  gachalog: 卡池进度

  #
  gacha_statistics: 卡池统计

# 保存的xlsx目录
xlsx_dir: ./data/

api: https://hk4e-api.mihoyo.com/event/gacha_info/api/

#gacha_analyzer_web: https://yuyumoko.github.io/genshin-gacha-analyzer/
gacha_analyzer_webs: [
    'https://genshin-gacha-analyzer.pages.dev/',
    'https://erinilis-gacha-analyzer.vercel.app/' ,
    'https://yuyumoko.github.io/genshin-gacha-analyzer/'
]